# Generated by Django 3.2.5 on 2021-07-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210720_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
